# Generated by Django 4.2.4 on 2023-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_devicelog_condition_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='condition_out',
            field=models.TextField(blank=True),
        ),
    ]
