# Generated by Django 4.2.4 on 2023-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicelog_condition_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='checked_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
