# Generated by Django 4.2.4 on 2023-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_devicelog_checked_out_alter_devicelog_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='checked_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
